pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/maymon-npst/ms-dependancy-cicd.git'
        SERVICE_NAME = 'service-d'
        IMAGE_NAME = 'service-d'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }
        stage('Build') {
            steps {
                echo 'Building Service D'
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Deploy') {
            steps {
                script {
                    echo 'Building Docker image for Service D'
                    sh "docker build -t ${IMAGE_NAME} ."

                    echo 'Running Service D Container'
                    sh "docker run -d --name ${SERVICE_NAME} -p 8083:8083 ${IMAGE_NAME}"
                }
            }
        }
    }
}
