pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/maymon-npst/ms-dependancy-cicd.git'
        SERVICE_NAME = 'service-a'
        IMAGE_NAME = 'service-a'
        CONTAINER_NAME = 'service-a'
        PORT = '8080'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Docker Build & Deploy') {
            steps {
                script {
                    sh '''
                    docker stop ${CONTAINER_NAME} || true
                    docker rm ${CONTAINER_NAME} || true
                    docker build -t ${IMAGE_NAME} .
                    docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} ${IMAGE_NAME}
                    '''
                }
            }
        }
        stage('Trigger Service B') {
            steps {
                script {
                    build job: 'service-b'
                }
            }
        }
    }
}
