pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/maymon-npst/ms-dependancy-cicd.git'
        SERVICE_NAME = 'service-b'
        YAML_FILE = 'service-b.yaml'
    }

    stages {
        stage('Wait for Service A') {
            steps {
                script {
                    build job: 'service-a', wait: true
                }
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }
        stage('Build') {
            steps {
                echo 'Building Service B'
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo 'Deploying Service B'
                    sh "kubectl apply -f ${YAML_FILE}"
                }
            }
        }
        stage('Trigger Service C') {
            steps {
                script {
                    build job: 'service-c'
                }
            }
        }
    }
}
